[build-system]
requires = [
    "setuptools>=51",
    "wheel"
]

build-backend = "setuptools.build_meta"


[tool.pytest.ini_options]
minversion = "7.0"
testpaths = [
    "test"
]
pythonpath = [
  "src"
]
